### ISSUE TITLE
Decide what to do about JSON API

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#12]
Code for JSON based compound API is still in the repository. It is not documented and, as far as I know, not in use by anyone. We should either document it and publish it or delete it. 

My general thought: people who want to do bulk calculations should use the component-contribution package. If they are sophisticated enough to call to an API, they can do that too. I would vote for deleting this code so we don't have to deal with the potential load on the server. 

Assigning to Elad for his thoughts, since he is more connected to the modeling world than I.

**Comment by flamholz** [comment]
Any thoughts on this Elad?

**Comment by eladnoor** [comment]
I vote for removing the API. Usually people want also to add non-KEGG compounds using their InChI description and that is only supported by the backend component-contribution package.
