### ISSUE TITLE
Fix download links

### ISSUE THREAD

**Issue by eladnoor** [eladnoor/equilibrator#13]
The links are broken, but also some filenames end with .gz and are not gzipped, or end with .csv and are gzipped.

**Comment by flamholz** [comment]
They all work for me locally on the fast_search branch. Where are they broken for you?
A

**Comment by eladnoor** [comment]
The links on the AWS server point to 127.0.0.1:8000
The gzip issue is solved.

**Comment by flamholz** [comment]
Should be fixed now. Please verify on your end. 
http://ec2-52-88-81-97.us-west-2.compute.amazonaws.com/download
