### ISSUE TITLE
Limit range of pH and I plots

### ISSUE THREAD

**Issue by eladnoor** [eladnoor/equilibrator#14]
Place a lower bound on the y-axis range for the pH/I plots. For very pH insensitive reactions, the range can sometimes be less than 0.1 kJ/mol, which is not significant, but makes it seem like the reaction does change with pH.

**Comment by flamholz** [comment]
I did this. I will push later when I have a connection that lets me SSH. I will close the bug then.

**Comment by flamholz** [comment]
See https://github.com/eladnoor/equilibrator/commit/82bd6d3d46eb879ce4e0dae037862f6cb0b6afaf
