### ISSUE TITLE
mM units on pathway analysis page?

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#15]
Ron suggested this so you wouldn't need to write extreme values. What does Elad think?

**Comment by eladnoor** [comment]
I think support both Unit='M' and Unit='mM' would be best (also for compatibility with ECM).

**Comment by flamholz** [comment]
This is done. See these changes.

https://github.com/eladnoor/equilibrator/commit/8d891b0fc0e93793d852d82ec5a02fde04bc3263
https://github.com/eladnoor/equilibrator/commit/410ca306a741794b55ef668922d3ab562fcf9528
https://github.com/eladnoor/equilibrator/commit/d107a1294783f5fbfe8202626d2000671986bafb
