### ISSUE TITLE
arren requests: override reaction dGs for pathway analysis

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#19]
I think the best way to do this is to include the dGs in the SBtab file output and then make the pathway analysis totally database independent. This would allow our output files to be used directly with Wolf's software.

Elad?

**Comment by flamholz** [comment]
One problem with this is that we would provide the reaction energies (Keqs) at a prespecified pH and I so you'd need to make new files if you wanted to test a different pH or ionic strength.

**Comment by eladnoor** [comment]
In addition, one must verify that the reaction energies satisfy the second law of thermodynamics.
A simple solution would be to write the values in the SBTab file and allow users to change them.

**Comment by flamholz** [comment]
I think this is what I was suggesting.

Just to check. By "satisfy the second law" you mean that they are all downhill at the MDF optimum, or something else? Because the optimizer requires this.

**Comment by eladnoor** [comment]
Sorry, I meant the first law. That means checking that the vector of standard energies is in the image of the stoichiometric matrix.

**Comment by flamholz** [comment]
to translate again for my understanding:
this verifies that there exist formation energies that could give rise to the reaction energies supplied, i.e. verifying conservation of energy. yes?

**Comment by eladnoor** [comment]
Exactly!

**Comment by flamholz** [comment]
https://github.com/eladnoor/equilibrator/commit/bd0216f7a42779b6672d2c3140bc041f1beee03c 

still need to verify that the vector of standard energies is in the image of the stoichiometric matrix.

**Comment by flamholz** [comment]
Elad -- suggestions about how to verify dgs in the colspace of S? I was thinking of using gaussian elimination to calculate the row-reduced echelon form of the augmented matrix, but numpy/scipy don't seem to come with an implementation. Do you have a different approach that you know works? Will it handle floating point issues?

**Comment by eladnoor** [comment]
In the past, I used SVD to calculate the orthogonal projection matrix for
the nullspace of S, and then checked that the vector of dgs is projected to
0 (numerically, the norm is < 1e-8). If this is not the case, we can
suggest (with user consent) to project the vector ourselves into the space
using the orthogonal projection (or do it automatically, while issuing a
warning).

**Comment by flamholz** [comment]
Elad - I implemented something similar with the penrose pseudo-inverse. The nullspace projection matrix for M equals I - MM+ where M+ is the pseudoinverse. I think this is equivalent to the SVD approach but was easier for me to understand. I checked this with some trivial examples. Here is the code. 

https://github.com/eladnoor/equilibrator/commit/3cf42bc9dee3cefce85c2cc6f7580f5242e1666b

**Comment by eladnoor** [comment]
Yes, that works too.
