### ISSUE TITLE
eQuilibrator server often crashes at setParseAction

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#2]
The WebFactional server will often crash with the error below, requiring a restart of Apache. It is unclear what exactly causes this problem, as it cannot be reproduced locally and the error seems to involve corruption of a PyParsing class. 

![screenshot_072816_1](https://cloud.githubusercontent.com/assets/2635393/17929646/c9774102-69cf-11e6-9cb3-f0e59c6e9fb9.png)

**Comment by flamholz** [comment]
Suggested solution is to move to AWS. Have not yet seen this issue pop up in the AWS environment.

**Comment by flamholz** [comment]
I think we can safely say this is resolved on the AWS server at this point - it's been running for about 3 weeks with no troubles. Elad do you agree?

**Comment by eladnoor** [comment]
I do!
