### ISSUE TITLE
default ionic_strength = 0.25 M? 

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#23]
Arren suggests this based on Alberty et al., Biophysical Chemistry 2011 (link below). However, this value is at the limit of the applicability of the Debye-Huckel approximation. Leaving to Elad to decide. 

http://www.sciencedirect.com/science/article/pii/S0301462211000640

**Comment by eladnoor** [comment]
I think it's not a good idea to change the defaults on eQuilibrator now, because most users will probably not notice it, and will be surprised by the change.

**Comment by flamholz** [comment]
agree. closing this
