### ISSUE TITLE
Add API for dG'0 of reactions given in KEGG IDs

### ISSUE THREAD

**Issue by eladnoor** [eladnoor/equilibrator#26]

**Comment by flamholz** [comment]
Why is this needed? Aren't there files for this? 
A

**Comment by eladnoor** [comment]
Not exactly, the files are for KEGG reactions, but if one wants to construct a new reaction from KEGG compound IDs, it's not so simple (don't forget we also want to curb the use of formation energies). Also, this could provide a chance to set the pH and I.

**Comment by flamholz** [comment]
Shouldn't we be encouraging people to use the local component contribution
code for this? I don't want to open up the server to being overloaded by
API users for something that doesn't intrinsically require an API.

I think it would be more worthwhile to make a nice script in
component-contribution that does this.
What do you think?
A

**Comment by eladnoor** [comment]
There is such a nice script already (albeit not that easy to find). It is, however, not completely trivial to install component-contribution and all its dependencies (unless you have a Debian-based OS). It's probably possible to make it easier if we want.

Also, I doubt that the server will be overloaded (we can probably limit the number of reactions to 10 just to be safe), and even if it will become too popular - that would prove that an API is easier to use than the script.

**Comment by flamholz** [comment]
If you build it I approve :)

**Comment by eladnoor** [comment]
the API is now available at [https://github.com/eladnoor/equilibrator-api](https://github.com/eladnoor/equilibrator-api).
