### ISSUE TITLE
make equilibrator 2.1 logo

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#3]
For the upcoming update including faster search and non-crashing.

**Comment by flamholz** [comment]
Assigning to Elad because I don't have all the fonts in the logo SVG file.

**Comment by flamholz** [comment]
the small 2.1 logo (equilibrator_logo_2_1_80px.png) contains the logo text which looks crappy. can you remove the text and blow up the scales a bit?

**Comment by eladnoor** [comment]
small logo is ready
