### ISSUE TITLE
"glycolate" returns "glycol"

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#49]
I think this is a similar bug to the O2 one we just fixed.

**Comment by eladnoor** [comment]
This is a weird bug. The text_exact query in Solr seems to return also matches to "glycol" even when the query is "glycolate". Then the scores we get are > 1 since they assume the matched string is always longer than the query. I don't think this is the same bug as the O2 one though.

**Comment by eladnoor** [comment]
Bug fixed, although it's more like a workaround.
Now, all matches are scored as if they are approximate matches, even if the are made via the "text__exact" option. The correct solution, however, would be to use the advanced capabilities of Solr to make the search faster and better. I redirect it to issue #35
