### ISSUE TITLE
Integrate fast_search branch into master

### ISSUE THREAD

**Issue by flamholz** [eladnoor/equilibrator#6]
Will not do this until we have fully tested the AWS instance and are ready to switch the DNS. 

Elad -- please verify that you are not relying on the master branch for anything other than equilibrator.weizmann.ac.il before I do this. You can then reassign to me and I'll handle the integration.

**Comment by eladnoor** [comment]
I confirm that the master branch is not used for anything else.

**Comment by flamholz** [comment]
This is done.
